[package]
name = "goraa"
edition = "2024"
version.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
portal-pc-asm-common.workspace = true
portal-solutions-asm-x86-64.workspace = true